# Generated by Django 3.2.9 on 2023-08-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_email',
            new_name='employees_email',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customer_name',
            new_name='employees_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customer_phone',
            new_name='employees_phone',
        ),
    ]
