# Generated by Django 3.2.9 on 2023-06-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='permissions',
        ),
        migrations.AddField(
            model_name='roles',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('ADMIN', 'ADMIN'), ('WORKER', 'WORKER')], max_length=30, unique=True),
        ),
    ]
