# Generated by Django 3.2.9 on 2023-07-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230629_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Worker', 'Worker')], max_length=30, unique=True),
        ),
    ]
